---
- hosts: all
  remote_user: pi
  become: true
  tasks:
  - name: install nodejs and npm
    package:
      name:
      - nodejs
      - npm
      - unclutter
  - name: upgrade to latest npm
    npm: name=npm@latest global=yes
  - name: install cncjs
    npm: name=cncjs global=yes unsafe_perm=yes
  - name: fetch lcd cncjs-pendant-tinyweb
    unarchive:
      src: https://github.com/cncjs/cncjs-pendant-tinyweb/archive/720ee08d3302251ba93030e5770a6aea8aef1e23.zip
      dest: /root
      remote_src: yes
      creates: /root/cncjs-pendant-tinyweb-720ee08d3302251ba93030e5770a6aea8aef1e23
  - name: create systemd unit file
    copy:
      dest: /etc/systemd/system/cncjs.service
      content: |
        [Unit]
        Description=cncjs
        After=network.target
        [Service]
        Type=simple
        Environment=HOME=/root/
        ExecStart=/usr/local/bin/cncjs --port 80 --controller Marlin --mount /pendant:/root/cncjs-pendant-tinyweb-720ee08d3302251ba93030e5770a6aea8aef1e23/src
        Restart=always
        [Install]
        WantedBy=multi-user.target
  - name: enable service
    systemd:
      name: cncjs
      state: started
      enabled: yes
  - name: create chromium autostart
    copy:
      dest: /home/pi/.config/lxsession/LXDE-pi/autostart
      content: |
        @xscreensaver -no-splash
        @xset s off
        @xset -dpms
        @xset s noblank
        @unclutter -root &
        @chromium-browser --kiosk http://localhost/pendant/
  - name: disable raspbian welcome screen
    file:
      state: absent
      path: /etc/xdg/autostart/piwiz.desktop
